# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-01 00:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_auto_20160120_1945'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('emp_id', models.ForeignKey(db_column='emp_id', default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='survey.Employee')),
                ('uid', models.ForeignKey(db_column='uid', default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='survey.People')),
            ],
        ),
        migrations.RemoveField(
            model_name='answer',
            name='emp_id',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='uid',
        ),
        migrations.AddField(
            model_name='answer',
            name='answer_set',
            field=models.ForeignKey(db_column='answer_set', default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='survey.AnswerSet'),
        ),
    ]
