# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-20 19:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):


    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('emp_id', models.IntegerField(primary_key=True, serialize=False)),
                ('unit', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='People',
            fields=[
                ('uid', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('qu_id', models.IntegerField(db_column='qu_id', primary_key=True, serialize=False)),
                ('qu_text', models.TextField(default='')),
                ('type', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='answer',
            name='emp_id',
            field=models.ForeignKey(db_column='emp_id', default=1, on_delete=django.db.models.deletion.CASCADE, to='survey.Employee'),
        ),
        migrations.AddField(
            model_name='answer',
            name='qu_id',
            field=models.ForeignKey(db_column='qu_id', default=1, on_delete=django.db.models.deletion.CASCADE, to='survey.Question'),
        ),
        migrations.AddField(
            model_name='answer',
            name='uid',
            field=models.ForeignKey(db_column='uid', default=1, on_delete=django.db.models.deletion.CASCADE, to='survey.People'),
        ),
    ]
